{% set name = "AnaCal" %}
{% set version = "0.4.0" %}
{% set sha256 = "a0e4aa5b99ab6528add1a94368821311caff775c6ee4928d05ff2d6450bd94b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  skip: true  # [py<310 or win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=38
    - fftw >=3.3
    - pybind11 >=2.2
    - fftw
    - pybind11
    - pip
  run:
    - python
    - fitsio
    - galsim
    - numpy
    - pydantic
    - jax
    - jaxlib

test:
  imports:
    - anacal

about:
  home: https://github.com/mr-superonion/AnaCal
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Analytical Shear Calibration"
  description: |
    AnaCal is a open-source software to derive linear shear response of
    observables measured from a 2D image.

extra:
  recipe-maintainers:
    - mr-superonion
