{% set name = "AnaCal" %}
{% set version = "0.7.1" %}
{% set sha256 = "3c18cc136b614d1408df911f587a089f815dc8749e093df2683731ab384312df" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  skip: true  # [py<310 or win]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ANACAL={{ version }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=38
    - setuptools_scm
    - fftw >=3.3
    - pybind11 >=2.2
    - pip
  run:
    - python
    - fitsio
    - galsim
    - numpy
    - pydantic
    - matplotlib-base

test:
  imports:
    - anacal

about:
  home: https://github.com/mr-superonion/AnaCal
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Analytical Shear Calibration"
  description: |
    AnaCal is a open-source software to derive linear shear response of
    observables measured from a 2D image.

extra:
  recipe-maintainers:
    - mr-superonion
